-- NR_Data_Recipes.lua -- not a kernel file: the craft-time conservation factors (Plan 11 Task 17).
-- GENERATED by tools/recipe_conservation.py from data/recipes.json and the item pass's data; do not
-- edit -- regenerate with --write. factor[recipe] = the inputs' kcal over the outputs' kcal, for each
-- recipe whose re-based outputs carry more than 1.10 x their inputs' energy (ruling 11).
local NR = NutritionRevamp
NR.data = NR.data or {}
NR.data.recipes = { factor = {
    ["MakeTortillaChips"] = 0.242611,
} }
