#!/usr/bin/env python3
"""Generate docs/reference/harness-commands.md from every TK.register("<name>", ...) site.

Each site carries, in the contiguous `--` comment run directly above it:
    -- @args <argument line, or (none)>
    -- @reply <reply keys in braces, or string, or unrecorded>
    -- @purpose <one line>
A site missing any key fails the run (exit 1). `--check` fails (exit 1) when the file on disk
differs from a fresh render — the generated table can never trail the Lua."""
import argparse, glob, os, re, sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUA_DIR = os.path.join(REPO_ROOT, "testing", "PZTestKit", "PZTestKit", "42", "media", "lua")
OUT = os.path.join(REPO_ROOT, "docs", "reference", "harness-commands.md")
SIDES = ("shared", "server", "client")
KEYS = ("args", "reply", "purpose")
REGISTER_RX = re.compile(r'TK\.register\(\s*"([^"]+)"')
KEY_RX = re.compile(r"^\s*--\s*@(args|reply|purpose)\s+(.*\S)\s*$")


def scan(lua_dir):
    sites = []
    for side in SIDES:
        for path in sorted(glob.glob(os.path.join(lua_dir, side, "*.lua"))):
            lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
            for i, line in enumerate(lines):
                m = REGISTER_RX.search(line)
                if not m:
                    continue
                block, j = {}, i - 1
                while j >= 0 and lines[j].lstrip().startswith("--"):
                    km = KEY_RX.match(lines[j])
                    if km and km.group(1) not in block:
                        block[km.group(1)] = km.group(2)
                    j -= 1
                sites.append({"name": m.group(1), "side": side, "file": side + "/" + os.path.basename(path),
                              "line": i + 1, "args": block.get("args", ""), "reply": block.get("reply", ""),
                              "purpose": block.get("purpose", ""), "missing": [k for k in KEYS if k not in block]})
    return sites


def _cell(text):
    return text.replace("|", "\\|")


def render(sites, label):
    order = {s: n for n, s in enumerate(SIDES)}
    rows = sorted(sites, key=lambda s: (s["name"], order[s["side"]]))
    names = len({s["name"] for s in rows})
    out = ["# Harness commands", "",
           "GENERATED by `python tools/bus_inventory.py` from every `TK.register(...)` site under `%s` — do not edit "
           "this file; edit the `-- @args` / `-- @reply` / `-- @purpose` block above the site and regenerate. "
           "One row per (name, side): a name registered on two sides takes different arguments per side. "
           "The reply-reading rules (the three buckets, `{}` for an empty list, `resolved`, `limit` is a BREAK) are "
           "`docs/platform/harness.md`, not this table. %d sites, %d names." % (label, len(rows), names), "",
           "| name | side | file:line | args | reply keys | purpose |", "|---|---|---|---|---|---|"]
    for s in rows:
        out.append("| `%s` | %s | `%s:%d` | %s | %s | %s |" % (
            s["name"], s["side"], s["file"], s["line"], _cell(s["args"]), _cell(s["reply"]), _cell(s["purpose"])))
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lua-dir", default=LUA_DIR)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--check", action="store_true", help="compare the file on disk with a fresh render; exit 1 on drift")
    a = ap.parse_args(argv)
    sites = scan(a.lua_dir)
    if not sites:
        print("no TK.register sites under %s" % a.lua_dir, file=sys.stderr)
        return 1
    missing = [s for s in sites if s["missing"]]
    if missing:
        for s in missing:
            print("%s:%d %s (%s): missing %s" % (s["file"], s["line"], s["name"], s["side"], ", ".join(s["missing"])), file=sys.stderr)
        print("%d of %d sites lack a complete @args/@reply/@purpose block" % (len(missing), len(sites)), file=sys.stderr)
        return 1
    label = os.path.relpath(a.lua_dir, REPO_ROOT).replace("\\", "/") if os.path.isabs(a.lua_dir) else a.lua_dir
    text = render(sites, label)
    if a.check:
        on_disk = open(a.out, encoding="utf-8", newline="").read().replace("\r\n", "\n") if os.path.exists(a.out) else ""
        if on_disk != text:
            old, new = on_disk.splitlines(), text.splitlines()
            first = next((n for n, (x, y) in enumerate(zip(old, new), 1) if x != y), min(len(old), len(new)) + 1)
            print("drift: %s differs from a fresh render at line %d (%d lines on disk, %d rendered); run without --check to regenerate"
                  % (a.out, first, len(old), len(new)))
            return 1
        print("in sync: %s (%d sites)" % (a.out, len(sites)))
        return 0
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    open(a.out, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d sites, %d names)" % (a.out, len(sites), len({s["name"] for s in sites})))
    return 0


if __name__ == "__main__":
    sys.exit(main())
